name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Backend image
      run: docker build . --file Dockerfile --tag mustafaapp/mern-project:backednd$(date +%s)
    - name: Build Frontend Image
      run: docker build /client --file Dockerfile --tag mustafaapp/mern-project:frontend(date +%s)
    - name: Pushing to Docker Hub
      run: docker push

#test run