name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Backend image
      run: docker build . --file Dockerfile --tag mustafaapp/mern-project:backednd$(date +%s)
    # - name: Change directory
    #   run: cd client
    - name: Build Frontend Image
      run: docker build client --file Dockerfile --tag mustafaapp/mern-project:frontend$(date +%s)
    - name: Pushing to Docker Hub Backend
      run: docker push mustafaapp/mernproject:backend$(date +%s)
    - name: Pushing to Docker Hub Frontend
      run: docker push mustafaapp/mernproject:frontend$(date +%s)

#test run