name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker Login
      env: 
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - name: Build the Backend image
      run: docker build . --file Dockerfile --tag mustafaapp/mern-project:backend$(date +%s)
    - name: Build Frontend Image
      run: docker build client --file Dockerfile --tag mustafaapp/mern-project:frontend$(date +%s)
    - name: Pushing to Docker Hub
      run: docker push ${{secrets.DOCKER_USERNAME}}/mern-project:backend$(date +%s)
